# Generated by Django 3.0.7 on 2022-12-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_category_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('technology', 'Technology'), ('culture', 'Culture'), ('opinion', 'Opinion'), ('travel', 'Travel')], default='world', max_length=50),
        ),
    ]
