# Generated by Django 3.0.7 on 2022-12-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221216_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.FileField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
